Disable matrix strategy "fail fast" feature (enabled by default).
Because one PHP version failed, all the others that were running tests ok were getting:
    Error: The operation was canceled.